version: "3.3"

services:
  backend:
      container_name: backend
      build:
        context: ./backend
        dockerfile: Dockerfile

      ports:
        - "8000:8000"

  frontend:
      container_name: frontend
      build:
        context: ./frontend
        dockerfile: Dockerfile

      ports:
        - "3000:4000"
